enum TransactionKind {
  MICROPAYMENT = 'MICROPAYMENT',
  ETHEREUM = 'ETHEREUM',
  SIGN = 'SIGN',
  OPEN_CHANNEL = 'OPEN_CHANNEL',
  CLOSE_CHANNEL = 'CLOSE_CHANNEL',
  INCOMING = 'INCOMING'
}

export default TransactionKind
